---
title: Été Meurtrier
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: etemeurtrier@contact.fr
description: 'Eté Meurtrier is launched in 2014 by Antonin Mesnil & Lilian Hardouineau.
  We work for art, music and immersive projects.

'
baseurl: 
url: http://ruff9.github.io
github_username: jekyll
markdown: kramdown
gems:
- jekyll-admin
